#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Hangman game
#

import random

WORDLIST_FILENAME = "words.txt"

def loadWords():
    """
    Returns a list of valid words. Words are strings of lowercase letters.
    
    Depending on the size of the word list, this function may
    take a while to finish.
    """
    print("Loading word list from file...")
    # inFile: file
    inFile = open(WORDLIST_FILENAME, 'r')
    # line: string
    line = inFile.readline()
    # wordlist: list of strings
    wordlist = line.split()
    print("  ", len(wordlist), "words loaded.")
    return wordlist

def chooseWord(wordlist):
    """
    wordlist (list): list of words (strings)

    Returns a word from wordlist at random
    """
    return random.choice(wordlist)


wordlist = loadWords()

def isWordGuessed(secretWord, lettersGuessed):
    '''
    secretWord: string, the word the user is guessing
    lettersGuessed: list, what letters have been guessed so far
    returns: boolean, True if all the letters of secretWord are in lettersGuessed;
      False otherwise
    '''
    value = 0
    
    for cha in secretWord:
        value += int(cha not in lettersGuessed)
        
    if value>0:
        return False
    else:
        return True


def getGuessedWord(secretWord, lettersGuessed):
    '''
    secretWord: string, the word the user is guessing
    lettersGuessed: list, what letters have been guessed so far
    returns: string, comprised of letters and underscores that represents
      what letters in secretWord have been guessed so far.
    '''
    string = ''
    
    for cha in secretWord:
        if cha in lettersGuessed:
            string += cha+' '
        else:
            string += '_'+' '
            
    return string[:-1]


def getAvailableLetters(lettersGuessed):
    '''
    lettersGuessed: list, what letters have been guessed so far
    returns: string, comprised of letters that represents what letters have not
      yet been guessed.
    '''
    
    string = ''
    lowers = 'abcdefghijklmnopqrstuvwxyz'
    for cha in lowers:
        if cha not in lettersGuessed:
            string += cha 
    return string
    

def hangman(secretWord):
    '''
    secretWord: string, the secret word to guess.

    Starts up an interactive game of Hangman.

    * At the start of the game, let the user know how many 
      letters the secretWord contains.

    * Ask the user to supply one guess (i.e. letter) per round.

    * The user should receive feedback immediately after each guess 
      about whether their guess appears in the computers word.

    * After each round, you should also display to the user the 
      partially guessed word so far, as well as letters that the 
      user has not yet guessed.

    Follows the other limitations detailed in the problem write-up.
    '''
    
    length = len(secretWord)
    lettersGuessed = []
    
    print('Welcome to the game Hangman!')
    print('I am thinking of a word that is '+str(length)+' letters long')
    
    mistakesMade = 0
    numGuesses = 8-mistakesMade
    
    while mistakesMade<8:
        numGuesses = 8-mistakesMade
        print('-----------')
        print('You have '+str(numGuesses)+' guesses left.')
        print('Available Letters: '+getAvailableLetters(lettersGuessed))
        
        Guess = input('Please guess a letter: ')
        guessLower = Guess.lower()
        
        if guessLower in lettersGuessed:
            print("Oops! You've already guessed that letter: "+getGuessedWord(secretWord, lettersGuessed))
        else:
            lettersGuessed.append(guessLower)
            if guessLower in secretWord:
                print('Good guess: '+getGuessedWord(secretWord, lettersGuessed))
            else:
                print("Oops! That letter is not in my word: "+getGuessedWord(secretWord, lettersGuessed))
                mistakesMade +=1
                
        if getGuessedWord(secretWord, lettersGuessed)==secretWord:
            print('-----------')
            print('Congratulations, you won!')
            break
        if mistakesMade ==8:
            print('-----------')
            print('Sorry, you ran out of guesses. The word was '+secretWord+' .')



secretWord = chooseWord(wordlist).lower()
hangman(secretWord)
